export const POSTS = {
  INITIALIZE: "POST_INITIALIZE",
  DELETE: "DELETE",
  EDIT: "EDIT",
  ADD: "ADD",
};

export const USERS = {
  INITIALIZE: "USERS_INITIALIZE",
  SIGN_UP: "SIGN_UP",
  UPDATE_FOLLOWERS: "UPDATE_FOLLOWERS",
  UPDATE_FOLLOWING: "UPDATE_FOLLOWING",
};

export const BOOKMARK = {
  INITIALIZE: "BOOKMARK_INITIALIZE",
  ADD_TO_BOOKMARK: "ADD_TO_BOOKMARK",
  REMOVE_FROM_BOOKMARK: "REMOVE_FROM_BOOKMARK",
};
