export const POSTS = {
  INITIALIZE: "POST_INITIALIZE",
};

export const USERS = {
  INITIALIZE: "USERS_INITIALIZE",
  UPDATE_FOLLOWERS: "UPDATE_FOLLOWERS",
  UPDATE_FOLLOWING: "UPDATE_FOLLOWING",
};
